### ISSUE TITLE
Feat: do we fancy a native Astro integration?

### ISSUE THREAD

**Issue by lirantal** [triggerdotdev/trigger.dev#345]
Hey folks!

Similar to the Express and Next.js packages, do we want to have a native Astro integration package as part of the officially provided packages from Trigger.dev?

See the following resources for more context:
- The Astro integration package: https://github.com/lirantal/triggerdev-astro-integration
- An example Astro project built with the above integration package: https://github.com/lirantal/trigger.dev-astro-example

Of course, that would be amazing! Here's everything I can think of at the moment that would be nice to do to get astro support in (this isn't to say you should do these, just that they should be done at some point):

```[tasklist]
### Tasks
- [x] #354 Add astro adapter package to packages in the monorepo as @trigger.dev/astro
- [ ] https://github.com/triggerdotdev/examples/pull/5 Add example Astro project to the examples repo: https://github.com/triggerdotdev/examples
- [x] Add a Quick start guide to the Trigger.dev/docs
- [x] Add support for astro in @trigger.dev/cli init
```

**Comment by ericallam** [comment]
Of course, that would be amazing! Here's everything I can think of at the moment that would be nice to do to get astro support in (this isn't to say you should do these, just that they should be done at some point):

- [ ] Add astro adapter package to `packages` in the monorepo as `@trigger.dev/astro` 
- [ ] Add example Astro project to the examples repo: https://github.com/triggerdotdev/examples
- [ ] Add a Quick start guide to the Trigger.dev/docs
- [ ] Add support for astro in `@trigger.dev/cli init`

**Comment by lirantal** [comment]
Sounds like a good list. I might just tackle them as one-by-one PRs to make it scoped and easier to review and iterate while working to land these in officially.

**Comment by lirantal** [comment]
@ericallam I think you can remove the bullet-list you created as I copied it over to my opening comment body as a tasklist so it is easier to track.

On that note, see first PR introduced for the astro package.

**Comment by ericallam** [comment]
@lirantal I detailed in a github discussion [here](https://github.com/triggerdotdev/trigger.dev/discussions/411) all the steps it would take to "officially" support another framework for Trigger.dev, thought you might find it interesting for the Astro work.

**Comment by lirantal** [comment]
Looks like this is now already shipped thanks to:
- [x] https://github.com/triggerdotdev/trigger.dev/pull/354
- [x] https://github.com/triggerdotdev/trigger.dev/issues/452

So I'd imagine we can close?

**Comment by matt-aitken** [comment]
@lirantal yep this is done, thanks a lot 🤩
