### ISSUE TITLE
[TRI-1249] Framework: Support for Remix

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#445]
# Build support for Remix into Trigger.dev

**_Please make sure to use Typescript for all code_**

### Task 1 - Remix Adaptor
- [ ] Create a new folder in `packages` called `remix`
- [ ] Create the adaptor for Remix. Use [this Next.js adaptor](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/nextjs/src/index.ts) code as reference when creating yours. Include all setup configurations to fully support the framework, e.g. Next.js requires adaptor support for both App and Pages routers.
- [ ] Create a basic Remix project that uses the adaptor in `examples/remix` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/remix` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference Remix where needed, including updating the the URLs.

### Task 3 – Write the documentation
- [ ] Locate the `manual-setup-remix.mdx` folder in `/docs/_snippets/`. Use this file to write your documentation, overwriting any contents of that file. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 4 – Update the webapp onboarding
- [ ] In the `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.remix` replace the `<FrameworkComingSoon/>` component with your new onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.
![CleanShot 2023-09-07 at 16 42 14](https://github.com/triggerdotdev/trigger.dev/assets/7555566/e235930d-f99e-408f-bc72-e98ce3d18892)

<sub>[TRI-1249](https://linear.app/triggerdotdev/issue/TRI-1249/framework-support-for-remix)</sub>

**Comment by Chigala** [comment]
Can I work on this?

**Comment by samejr** [comment]
> Can I work on this?

We're just about to merge a PR in the next hour or 2 which will allow you to work on this – and absolutely, you can claim this one. We will attach a bounty to this too.

**Comment by Chigala** [comment]
Thanks!

**Comment by samejr** [comment]
@Chigala This issue is ready for you now!

**Comment by samejr** [comment]
@Chigala i've assigned this issue to you too. If you think you are attempting too many or want to give some to others, let me know.

**Comment by rishi-raj-jain** [comment]
@samejr 

Can I pick this one up?

**Comment by Chigala** [comment]
@rishi-raj-jain I've started work on this

**Comment by rishi-raj-jain** [comment]
@Chigala OK

**Comment by samejr** [comment]
@rishi-raj-jain, @Chigala is making an attempt at this one and I've already assigned the issue to him. Redwood.js issue is still free?

**Comment by rishi-raj-jain** [comment]
Yeah, I picked that. Crazy contributions to 3 of them by Chigala already!
