### ISSUE TITLE
[TRI-1250] Framework: support for Nuxt

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#447]
# Build support for Nuxt into Trigger.dev

***Please make sure to use Typescript for all code***

### Task 1 - Nuxt Adaptor

- [ ] Create a new folder in `packages` called `nuxt`
- [ ] Create the adaptor for Nuxt. Use [this Next.js adaptor](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/nextjs/src/index.ts) code as reference when creating yours. Include all setup configurations to fully support the framework, e.g. Next.js requires adaptor support for both App and Pages routers.
- [ ] Create a basic Nuxt project that uses the adaptor in `examples/nuxt` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a [README.md](http://README.md) file

- [ ] Create a new [README.md](http://README.md) file inside the `packages/nuxt` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference Nuxt where needed, including updating the the URLs.

### Task 3 – Write the documentation

- [ ] Locate the `manual-setup-nuxt.mdx` folder in `/docs/_snippets/`. Use this file to write your documentation, overwriting any contents of that file. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 4 – Update the webapp onboarding

- [ ] In the `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.nuxt` replace the `<FrameworkComingSoon/>` component with your new onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.

![](https://uploads.linear.app/80a884b1-f84c-49d6-91db-07a391663d20/8994af96-bd76-4767-a1f1-0bea2cc98e2a/d235a893-1c57-4645-8651-432f7764357d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzgwYTg4NGIxLWY4NGMtNDlkNi05MWRiLTA3YTM5MTY2M2QyMC84OTk0YWY5Ni1iZDc2LTQ3NjctYTFmMS0wYmVhMmNjOThlMmEvZDIzNWE4OTMtMWM1Ny00NjQ1LTg2NTEtNDMyZjc3NjQzNTdkIiwiaWF0IjoxNzExNjM0MDYzLCJleHAiOjE3MTE3MjA0NjN9.lWJgPEDs19uLEJ9IKBe4fjK9lSnMGbInwng4SH6Fzj8)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1250](https://linear.app/triggerdotdev/issue/TRI-1250/framework-support-for-nuxt)</sub>

**Comment by neo773** [comment]
@samejr Can I assigned to this as I was the first one to claim the issue?

**Comment by samejr** [comment]
@neo773 i've just assigned you to this issue for this attempt.

**Comment by playgude2** [comment]
Is this issue is still open ?
Can I look into this issue?

**Comment by rishi-raj-jain** [comment]
@samejr 

I think this issue is resolved?

**Comment by samejr** [comment]
This issue hasn't been merged yet, but I've awarded the bounty as the PR is good. We're still working out how best to proceed with some of these frameworks.

**Comment by IvanBernatovic** [comment]
Any news on this? #460 looks good, why not merge the `framework/nuxt `branch and put Beta label on it or something to get more people testing it out? I'd be happy to test if needed.

**Comment by genu** [comment]
I'd like to try this out in a nuxt project. Is there anything left pending for this?

**Comment by nikuscs** [comment]
Sorry for the pressure, but when will this eventually make it to the master?

**Comment by samejr** [comment]
There is a branch with the Nuxt package from that PR but we haven't had time to test and add CLI automatic installation support.

For now, you can use this file as reference: https://github.com/triggerdotdev/trigger.dev/blob/frameworks/nuxt/packages/nuxtjs/src/index.ts

That is the only code required to create an `api/trigger` POST route in your app. This is all that the framework packages do. You will have to follow some other steps like setting up environment variables, you can use the Express manual setup guide for now: https://trigger.dev/docs/documentation/guides/manual/express

**Comment by IvanBernatovic** [comment]
@samejr I tested those PR diffs in my Nuxt project and managed to get it working. 
To everyone who's gonna test Nuxt integration like this: The biggest bump was verifying the Dev environment key. To validate it I had to run `npx @trigger.dev/cli@latest init` which also wrongfully recognized Nuxt project as Remix project and added unnecessary npm dependency. But it's easy to clean it up and kind of expected since published npm package doesn't have Nuxt support yet.

@samejr The reason this took a long time is I assumed `npx @trigger.dev/cli@latest init` only adds required dependencies and fields to package.json so I ignored it. During that time I couldn't get setup working due to unverified API key, as mentioned before.

**Comment by platform-kit** [comment]
Hi @IvanBernatovic, any update on shipping Nuxt compatability?

**Comment by madebyfabian** [comment]
Hi there! Would love to see this supported by default, since I successfully used trigger.dev in a Next.js project, I want to also migrate to it in other Nuxt projects. Is there anything we can do to get this merged?

**Comment by samejr** [comment]
Hey, we won’t be providing an official Nuxt package for v2. But if someone has created a good working example we’re more than happy to share it widely.

Instead, v3 will be shipping next month and will not require any framework specific code: https://trigger.dev/blog/v3-announcement

**Comment by Flowko** [comment]
that sounds great, but how long till v3 is out of beta ? would love to use trigger.dev

**Comment by samejr** [comment]
Hey @Flowko - we're about 1 week away from releasing the developer preview. We'll be dropping an announcement as soon as it's ready on [Twitter(X)](https://twitter.com/triggerdotdev) and in our [Discord](https://trigger.dev/discord) if you want to get notified.

**Comment by pi0** [comment]
Hi. Nitro/Nuxt maintainer here! Please let me know if need any helps, particularly I'm interested to see how we can integrate triggerdev with [nitro tasks API](https://nitro.unjs.io/guide/tasks) and good luck with v3 release 👍🏼

**Comment by samejr** [comment]
Hey @pi0 thanks for offering to help 👍. We're slowly letting people into v3 now which is framework agnostic so it should just work with Nuxt. We do have users with Nuxt apps so I might reach out for help if we have any issues testing as none of us have used Nuxt. 😀 Very happy to discuss nitro tasks too – maybe [on our Discord](https://trigger.dev/discord) is best for that discussion.

**Comment by DavidDeSloovere** [comment]
If you get Pooya on board for this, it will only get better.

**Comment by matt-aitken** [comment]
I'm closing this issue because in v3 the product is framework independent and works with Nuxt. https://trigger.dev/docs/quick-start
