### ISSUE TITLE
[TRI-1251] Framework: support for Redwood.js

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#448]
# Build support for Redwood into Trigger.dev

**_Please make sure to use Typescript for all code_**

### Task 1 - Redwood Adaptor
- [ ] Create a new folder in `packages` called `redwood`
- [ ] Create the adaptor for Redwood. Use [this Next.js adaptor](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/nextjs/src/index.ts) code as reference when creating yours. Include all setup configurations to fully support the framework, e.g. Next.js requires adaptor support for both App and Pages routers.
- [ ] Create a basic Redwood project that uses the adaptor in `examples/redwood` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/redwood` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference Redwood where needed, including updating the the URLs.

### Task 3 – Write the documentation
- [ ] Locate the `manual-setup-redwood.mdx` folder in `/docs/_snippets/`. Use this file to write your documentation, overwriting any contents of that file. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 4 – Update the webapp onboarding
- [ ] In the `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.redwood` replace the `<FrameworkComingSoon/>` component with your new onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.
![CleanShot 2023-09-07 at 16 42 14](https://github.com/triggerdotdev/trigger.dev/assets/7555566/e235930d-f99e-408f-bc72-e98ce3d18892)

<sub>[TRI-1251](https://linear.app/triggerdotdev/issue/TRI-1251/framework-support-for-redwoodjs)</sub>

**Comment by rishi-raj-jain** [comment]
@samejr

Can I pick this one up?

/attempt #448

**Comment by rishi-raj-jain** [comment]
Can you assign this to me?

**Comment by samejr** [comment]
This one is yours 👍

**Comment by rishi-raj-jain** [comment]
Thanks, looks like Redwood is tough for people :)

**Comment by rishi-raj-jain** [comment]
I'm working on it.

**Comment by matt-aitken** [comment]
This issue is currently on pause because RedwoodJS currently only supports the Yarn package manager: https://github.com/redwoodjs/redwood/issues/2907. 

This means that it doesn't play nicely inside our repo. If we could get it work nicely we'd also have to make it so all the instructions in the app and docs only used yarn.

**Comment by matt-aitken** [comment]
Additionally here's a comment with a video showing the problem: https://github.com/triggerdotdev/trigger.dev/pull/598#issuecomment-1754963307

**Comment by Bhavyajain21** [comment]
Is this issue still on pause?
 @matt-aitken

**Comment by samejr** [comment]
Hey, we won’t be providing an official Redwood package for v2. Instead, v3 will be shipping in a few weeks and will not require any framework specific code: https://trigger.dev/blog/v3-announcement

**Comment by samejr** [comment]
Hey @HyperDanisH this bounty has already been claimed

**Comment by HyperDanisH** [comment]
@samejr It's fine, I can further look for other bounties.

**Comment by Oshinx** [comment]
/attempt https://github.com/triggerdotdev/trigger.dev/issues/448

**Comment by samejr** [comment]
Hey @Oshinx please don’t attempt this. This is a very old issue that I’m closing now.
