### ISSUE TITLE
[TRI-1252] Framework: support for Nest.js

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#449]
# Build support for Nest.js into Trigger.dev

**_Please make sure to use Typescript for all code_**

### Task 1 - Nest.js Adaptor
- [ ] Create a new folder in `packages` called `nestjs`
- [ ] Create the adaptor for Nest.js. Use [this Next.js adaptor](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/nextjs/src/index.ts) code as reference when creating yours. Include all setup configurations to fully support the framework, e.g. Next.js requires adaptor support for both App and Pages routers.
- [ ] Create a basic Nest.js project that uses the adaptor in `examples/nestjs` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/nestjs` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference Nest.js where needed, including updating the the URLs.

### Task 3 – Write the documentation
- [ ] Locate the `manual-setup-nestjs.mdx` folder in `/docs/_snippets/`. Use this file to write your documentation, overwriting any contents of that file. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 4 – Update the webapp onboarding
- [ ] In the `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.nestjs` replace the `<FrameworkComingSoon/>` component with your new onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.
![CleanShot 2023-09-07 at 16 42 14](https://github.com/triggerdotdev/trigger.dev/assets/7555566/e235930d-f99e-408f-bc72-e98ce3d18892)

<sub>[TRI-1252](https://linear.app/triggerdotdev/issue/TRI-1252/framework-support-for-nestjs)</sub>

**Comment by mnmt7** [comment]
@samejr Can you please assign this issue to me?

**Comment by samejr** [comment]
@mnmt7 ive assigned you for this attempt. Good luck, let me know if you need anything!

**Comment by akhill10** [comment]
@mnmt7 I'm checking since you're already attempting Support for Fastify. Can I take this up, if it's okay for you?

**Comment by mnmt7** [comment]
@akhill10, for now I would like to do both. However, If I end up getting into some issue, I would be more than happy to pass it to you.

**Comment by neo773** [comment]
I think it's a little unfair to hoard attempts when you can only do one at a time. In the meantime, someone could have completed it.

**Comment by ericallam** [comment]
@mnmt7 we appreciate the enthusiasm but since these are pretty large issues, I think it probably makes sense do just one at a time and leave the other issues for others to do in the meantime
