### ISSUE TITLE
[TRI-1253] Framework: support for Fastify

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#450]
# Build support for Fastify into Trigger.dev

**_Please make sure to use Typescript for all code_**

### Task 1 - Fastify Adaptor
- [ ] Create a new folder in `packages` called `fastify`
- [ ] Create the adaptor for Fastify. Use [this Next.js adaptor](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/nextjs/src/index.ts) code as reference when creating yours. Include all setup configurations to fully support the framework, e.g. Next.js requires adaptor support for both App and Pages routers.
- [ ] Create a basic Fastify project that uses the adaptor in `examples/fastify` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/fastify` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference Fastify where needed, including updating the the URLs.

### Task 3 – Write the documentation
- [ ] Locate the `manual-setup-fastify.mdx` folder in `/docs/_snippets/`. Use this file to write your documentation, overwriting any contents of that file. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 4 – Update the webapp onboarding
- [ ] In the `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.fastify` replace the `<FrameworkComingSoon/>` component with your new onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.
![CleanShot 2023-09-07 at 16 42 14](https://github.com/triggerdotdev/trigger.dev/assets/7555566/e235930d-f99e-408f-bc72-e98ce3d18892)

<sub>[TRI-1253](https://linear.app/triggerdotdev/issue/TRI-1253/framework-support-for-fastify)</sub>

**Comment by mnmt7** [comment]
@samejr Can you please assign this issue to me?

**Comment by samejr** [comment]
@mnmt7 this attempt is all yours – let me know if you run into anything.

**Comment by akhill10** [comment]
As there was activity on the issue past week, So worked on it in background. Feel free to reject my PR as I am not the first one to claim the bounty.
 
But this PR uses [Fastiy Plugin ](https://fastify.dev/docs/latest/Reference/Plugins/) that allows user to extend their functionalities and is a powerful tool to build a modular application rather than the addHook approach

**Comment by samejr** [comment]
Thanks @akhill10 we'll still check it out 👍

**Comment by samejr** [comment]
This issue hasn't been merged yet, but I've awarded the bounty as the PR is good. We're still working out how best to proceed with some of these frameworks.

**Comment by qlaffont** [comment]
any update on this issue ?

**Comment by samejr** [comment]
We won’t be providing an official Fastify package for v2. But if someone has created a good working example we’re more than happy to share it widely.

Instead, v3 will be shipping next month and will not require any framework specific code: https://trigger.dev/blog/v3-announcement

**Comment by asr-alurisanthoshreddy** [comment]
Is this issue need any further development, as i can see it is still open.

**Comment by samejr** [comment]
Hey @asr-alurisanthoshreddy this is an old issue associated with v2. We're only developing for our v3 platform now so closing this issue.
