### ISSUE TITLE
[TRI-1254] Framework: support for Express

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#451]
# Build support for Express into Trigger.dev

**_Please make sure to use Typescript for all code_**

### Task 1 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/express` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference Express where needed, including updating the the URLs.

### Task 2 – Write the documentation
- [ ] Locate the `manual-setup-express.mdx` folder in `/docs/_snippets/`. Use this file to write your documentation, overwriting any contents of that file. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 3 – Update the webapp onboarding
- [ ] In the `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.express` replace the `<FrameworkComingSoon/>` component with your new onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.
![CleanShot 2023-09-07 at 16 42 14](https://github.com/triggerdotdev/trigger.dev/assets/7555566/e235930d-f99e-408f-bc72-e98ce3d18892)

<sub>[TRI-1254](https://linear.app/triggerdotdev/issue/TRI-1254/framework-support-for-express)</sub>

**Comment by MAYANK-TRIPATH** [comment]
@samejr I am attempting this one :)

**Comment by rishi-raj-jain** [comment]
I think with Trigger it's like the one who does it the first

**Comment by rishi-raj-jain** [comment]
Classic case of clash!

**Comment by samejr** [comment]
We'll done both! If I get time over the weekend I'll test and review. Otherwise, I'll get to it Monday.

**Comment by ayusham001** [comment]
Hi @samejr, I did not notice that the bounty was already assigned, I believed the previous norms were still being followed and I pushed the PR first. Also, It seems like 5/6 files submitted by @MAYANK-TRIPATH are copied.
Please look into the matter.

**Comment by ayusham001** [comment]
Hi @samejr, I did not notice that the bounty was already assigned, I believed the previous norms were still being followed and I pushed the PR first, that was a mistake on my part. I know it will be time-consuming but please look into my PR as well and review it once.

**Comment by samejr** [comment]
@ayusham001 all issues are first-come-first-served so I'll review PRs in order. The first person to claim the issue also gets it assigned to them too. 

Ultimately I am looking for quality, not speed so the best way to win bounties, especially if multiple people have attempted it, is to spend the time to do a great job. 

I'll try get round to reviewing the PRs this weekend but more likely Monday.

**Comment by ayusham001** [comment]
@samejr Yes sure you may do what you find fit, I totally understand and it is only fair that you do so, I only wanted you to review my PR as well and provide me with your feedback which shall be valuable to me. 
Yes, I do keep in mind that the quality of my work stays competent.

Sure Monday works.
Thank you.

**Comment by melsonic** [comment]
@samejr Is this issue still open?

**Comment by melsonic** [comment]
@samejr can I work on this issue?

**Comment by rishi-raj-jain** [comment]
@samejr Can I work on this one?

**Comment by matt-aitken** [comment]
This was completed internally as none of the submitted PRs had accurate instructions that would result in a working Express + Trigger project
