### ISSUE TITLE
[TRI-1255] Framework: support for Astro

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#452]
# Build support for Astro into Trigger.dev

**_Please make sure to use Typescript for all code_**

### Task 1 - Astro Adaptor
- [ ] Create a new folder in `packages` called `astro`
- [ ] Create the adaptor for Astro. Use [this Next.js adaptor](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/nextjs/src/index.ts) code as reference when creating yours. Include all setup configurations to fully support the framework, e.g. Next.js requires adaptor support for both App and Pages routers.
- [ ] Create a basic Astro project that uses the adaptor in `examples/astro` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/astro` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference Astro where needed, including updating the the URLs.

### Task 3 – Write the documentation
- [ ] Locate the `manual-setup-astro.mdx` folder in `/docs/_snippets/`. Use this file to write your documentation, overwriting any contents of that file. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 4 – Update the webapp onboarding
- [ ] In the `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.astro` replace the `<FrameworkComingSoon/>` component with your new onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.
![CleanShot 2023-09-07 at 16 42 14](https://github.com/triggerdotdev/trigger.dev/assets/7555566/e235930d-f99e-408f-bc72-e98ce3d18892)

<sub>[TRI-1255](https://linear.app/triggerdotdev/issue/TRI-1255/framework-support-for-astro)</sub>

**Comment by Chigala** [comment]
@lirantal has already done most of this, so I think we'll just convert the current Astro adapter to typescript and do the necessary documentation.

**Comment by samejr** [comment]
Yes, great idea. Please convert it to TS 👍

**Comment by rishi-raj-jain** [comment]
@samejr

Can I pick this one up?

**Comment by samejr** [comment]
@Chigala is taking on this one.

**Comment by neo773** [comment]
@ericallam Since, Chigala is already attempting `SvelteKit` and `Remix` could I assigned to this?

**Comment by samejr** [comment]
@Chigala has already claimed this one so check with him first to see if he's okay to let you have a first attempt.

**Comment by Chigala** [comment]
@neo773 I have the docs ready for this. Someone already worked on this before. I was working on sveltekit support and had discussions about this on discord way before there was a bounty attached to it. Prepared documentations for the Astro support too, I didn't know bounties would get attached to them. It only makes sense to attempt them when bounties were placed on them since I was already working on them. Just putting this out there incase maybe it looks likes I'm taking everything.

**Comment by lirantal** [comment]
Great work @Chigala shipping this 🚀
