### ISSUE TITLE
[TRI-1256] Framework: support for SvelteKit

### ISSUE THREAD

**Issue by samejr** [triggerdotdev/trigger.dev#453]
# Build support for SvelteKit into Trigger.dev

**_Please make sure to use Typescript for all code_**

### Task 1 - SvelteKit Adaptor
- [ ] Create a new folder in `packages` called `svelteKit`
- [ ] Create the adaptor for SvelteKit. Use [this Next.js adaptor](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/nextjs/src/index.ts) code as reference when creating yours. Include all setup configurations to fully support the framework, e.g. Next.js requires adaptor support for both App and Pages routers.
- [ ] Create a basic SvelteKit project that uses the adaptor in `examples/svelteKit` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/svelteKit` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference SvelteKit where needed, including updating the the URLs.

### Task 3 – Write the documentation
- [ ] Locate the `manual-setup-svelteKit.mdx` folder in `/docs/_snippets/`. Use this file to write your documentation, overwriting any contents of that file. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 4 – Update the webapp onboarding
- [ ] In the `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.svelteKit` replace the `<FrameworkComingSoon/>` component with your new onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.
![CleanShot 2023-09-07 at 16 42 14](https://github.com/triggerdotdev/trigger.dev/assets/7555566/e235930d-f99e-408f-bc72-e98ce3d18892)

<sub>[TRI-1256](https://linear.app/triggerdotdev/issue/TRI-1256/framework-support-for-sveltekit)</sub>

**Comment by Chigala** [comment]
I already have ongoing work currently on this. I have the svelte kit adapter and the @trigger.dev/svelte package ready. Ran into a bug that slowed the development

**Comment by samejr** [comment]
@Chigala yes please keep working on this 👍  – and i've added a full bounty to this issue regardless.

**Comment by AlbertMarashi** [comment]
What about v3?

**Comment by samejr** [comment]
v3 is architected fundamentally differently to v2 and is framework agnostic.

**Comment by AlbertMarashi** [comment]
@samejr but then how do I access things that svelte exposes like `$app/environment` or `$env/static/private`?

**Comment by AlbertMarashi** [comment]
Anyhow, I wrote an extension that exposes `.env` variables and `process.env` variables such that they resolve for SvelteKit's `$env` modules

```
import { defineConfig } from "@trigger.dev/sdk/v3"
import type { BuildExtension } from "@trigger.dev/build"
import { existsSync, readFileSync } from "node:fs"
import { parse } from "dotenv"

export default defineConfig({
    project: "XXXX",
    runtime: "node",
    build: {
        extensions: [
            svelteKitBuildExtension()
        ]
    },
    logLevel: "log",
    // The max compute seconds a task is allowed to run. If the task run exceeds this duration, it will be stopped.
    // You can override this on an individual task.
    // See https://trigger.dev/docs/runs/max-duration
    maxDuration: 3600,
    retries: {
        enabledInDev: true,
        default: {
            maxAttempts: 3,
            minTimeoutInMs: 1000,
            maxTimeoutInMs: 10000,
            factor: 2,
            randomize: true,
        },
    },
    
    dirs: ["./src/trigger"],
})


function svelteKitBuildExtension(): BuildExtension {
    return {
        name: "sveltekit-build-extension",
        onBuildStart: async ctx => {
            ctx.registerPlugin({
                name: "sveltekit-build-extension",
                setup: async build => {
                    const envFilter = /\$env\/(static|dynamic)\/(private|public)/

                    build.onResolve({
                        filter: envFilter,
                    }, args => ({
                        path: args.path,    
                        namespace: "env",
                    }))

                    build.onLoad({
                        filter: envFilter,
                        namespace: "env"
                    }, args => {
                        const [, type, scope] = args.path.split("/")
                        return get_module_return_types(
                            type as "static" | "dynamic", 
                            scope as "public" | "private",
                        )
                    })
                }
            })

        }
    }
}


function get_module_return_types(type: "static" | "dynamic", scope: "public" | "private"): {
    contents: string
    loader: "js" | "json"
} {
    const env = parse(readFileSync(".env", "utf8"))
    const pred = scope === "public" ? (key: string) => key.startsWith("PUBLIC_") : () => true
    const vars = Object.entries(env).filter(([key]) => pred(key))

    switch (type) {
        case "static": return {
            loader: "json",
            contents: JSON.stringify(vars)
        }
        case "dynamic": return {
            contents: JSON.stringify({ env: vars }),
            loader: "json"
        }
    }
}
```

**Comment by samejr** [comment]
This is really cool and we should create an official extension from this!

I can see you're chatting to matt in Discord about this so i'll keep the convo over there 👍

**Comment by kirso** [comment]
> This is really cool and we should create an official extension from this!
> 
> I can see you're chatting to matt in Discord about this so i'll keep the convo over there 👍

I know this is closed but was it made official? Quite frankly I had a lot of issues with triggerkit generating bad types and messing with all my validations and the old way still pushes a bunch of re-exports and using node.

Any chance there is an improvement planned on this?
