### ISSUE TITLE
[TRI-1372] Add a framework adaptor for SolidStart, with manual setup docs

### ISSUE THREAD

**Issue by matt-aitken** [triggerdotdev/trigger.dev#569]
**_Please make sure to use Typescript for all code_**

### Task 1 - SolidStart Adaptor
- [ ] Create a new folder in `packages` called `solidstart`
- [ ] Create the adaptor for SolidStart. Use [this Next.js adaptor](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/nextjs/src/index.ts) code as reference when creating yours. Include all setup configurations to fully support the framework, e.g. Next.js requires adaptor support for both App and Pages routers.
- [ ] Create a basic SolidStart project that uses the adaptor in `references/solidstart` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/solidstart` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference SolidStart where needed, including updating the the URLs.

### Task 3 – Write the documentation
- [ ] Create a manual setup guide in the docs. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 4 – Update the webapp onboarding
- [ ] Create a `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.solidstart` with the onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.
![CleanShot 2023-09-07 at 16 42 14](https://github.com/triggerdotdev/trigger.dev/assets/7555566/e235930d-f99e-408f-bc72-e98ce3d18892)

<sub>[TRI-1372](https://linear.app/triggerdotdev/issue/TRI-1372/add-a-framework-adaptor-for-solidstart-with-manual-setup-docs)</sub>

**Comment by ShatilKhan** [comment]
I'd like to work on this, please assign me

**Comment by matt-aitken** [comment]
Framework packages are not needed in v3, it's framework agnostic. v2 is deprecated as of Jan 31 2025
