### ISSUE TITLE
[TRI-1400] Create a Gadget adapter

### ISSUE THREAD

**Issue by ericallam** [triggerdotdev/trigger.dev#615]
@edlaver has written up a detailed guide on how to use Trigger.dev with [Gadget.dev](https://gadget.dev/) that we should use to create an official adapter package at `@trigger.dev/gadget`.

https://gist.github.com/edlaver/e9e0f9bf48e2b5674659c2eb091b6f7b

**_Please make sure to use Typescript for all code_**

### Task 1 - Gadget.dev Adaptor
- [ ] Create a new folder in `packages` called `gadget`
- [ ] Create the adaptor for Gadget following the gist above
- [ ] Create a basic Gadget.dev project that uses the adaptor in `references/gadget` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/gadget` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference gadget.dev where needed, including updating the the URLs.

### Task 3 – Write the documentation
- [ ] Create the `manual-setup-gadget.mdx` file in `/docs/_snippets/`. Use this file to write your documentation. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

<sub>[TRI-1400](https://linear.app/triggerdotdev/issue/TRI-1400/create-a-gadget-adapter)</sub>

**Comment by matt-aitken** [comment]
v2 is deprecated as of Jan 31 2025
